In [7]:
from datasets import load_dataset

ds = load_dataset("BrightData/Goodreads-Books")
df = ds["train"].to_pandas()

'(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: 0884275f-5be2-4866-9bd8-37ea0f66141a)')' thrown while requesting HEAD https://huggingface.co/datasets/BrightData/Goodreads-Books/resolve/main/README.md
Retrying in 1s [Retry 1/5].

In [8]:
df

,url,id,name,author,star_rating,num_ratings,num_reviews,summary,genres,first_published,about_author,community_reviews,kindle_price
0,https://www.goodreads.com/book/show/1047836.Ho...,1047836.Horror_Film_Directors_1931_1990,"Horror Film Directors, 1931-1990","[""Dennis Fischer""]",4.29,7.0,NaN,An exhaustive study of the major directors of ...,None,11/1/1991,"{""name"":""Dennis Fischer"",""num_books"":14}","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
1,https://www.goodreads.com/book/show/4089333-au...,4089333-australian-urban-planning,"Australian Urban Planning: New Challenges, New...","[""Brendan Gleeson""]",3.00,1.0,NaN,"Designed for use by academics, students, plann...",None,2/1/2000,"{""name"":""Brendan Gleeson"",""num_books"":28}","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
2,https://www.goodreads.com/book/show/26764878-m...,26764878-morgen-ohne-gestern,Morgen ohne gestern: Roman,"[""Regina Nössler""]",3.00,2.0,NaN,Christine Hoffmann wacht eines Morgens im Kran...,None,9/18/2015,"{""name"":""Regina Nössler"",""num_books"":28,""num_f...","{""1_stars"":{""reviews_num"":1,""reviews_percentag...","""$10.89"""
3,https://www.goodreads.com/book/show/23656944-z...,23656944-zen-and-the-art-of-recording,Zen and the Art of Recording,"[""Mixerman""]",4.19,88.0,4.0,"In this book, the third in the Zen and the Art...","[""Music"",""Nonfiction""]",10/1/2014,"{""name"":""Mixerman"",""num_books"":15,""num_followe...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...","""$24.09"""
4,https://www.goodreads.com/book/show/26761586-t...,26761586-the-big-book-of-codewords,The Big Book Of Codewords,"[""Parragon Books""]",4.50,6.0,NaN,500 codeword puzzles in one great book!,None,9/5/2015,"{""name"":""Parragon Books"",""num_books"":6068,""num...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6389854,https://www.goodreads.com/book/show/13407010-t...,13407010-the-world-of-randolph-bourne,The World of Randolph Bourne,"[""Randolph Bourne""]",3.50,2.0,NaN,None,None,1/1/1965,"{""name"":""Randolph Bourne"",""num_books"":24,""num_...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
6389855,https://www.goodreads.com/book/show/22747427-2...,22747427-25-cosas-que-todos-los-marineros-nece...,25 Cosas que todos los marineros necesitan (Sa...,"[""Lance Gettler""]",3.67,9.0,NaN,Una cosa que he aprendido es que el océano fav...,None,9/9/2013,"{""name"":""Lance Gettler"",""num_books"":9,""num_fol...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...","""$0.99"""
6389856,https://www.goodreads.com/book/show/18948207-u...,2425666.Untouchables,"Untouchables: Dirty Cops, Bent Justice and Rac...","[""Michael Gillard""]",3.96,105.0,6.0,'Untouchables' is an integrity test on Scotlan...,"[""Nonfiction"",""Crime"",""True Crime"",""Reference""...",1/1/2004,"{""name"":""Michael Gillard"",""num_books"":6,""num_f...","{""1_stars"":{""reviews_num"":2,""reviews_percentag...",None
6389857,https://www.goodreads.com/book/show/19194625-f...,129550989-famous-flyers-and-their-famous-flights,Famous flyers and their famous flights,"[""Capt. J.J. GRAYSON""]",5.00,1.0,NaN,This book was converted from its physical edit...,None,3/30/2011,"{""name"":""Capt. J.J. GRAYSON""}","{""1_stars"":{""reviews_num"":0,""reviews_percentag...","""$0.00"""
6389858,https://www.goodreads.com/book/show/20448502-t...,22541446-the-mcbrides,The McBrides: A Romance of Arran,"[""John Sillars""]",4.50,2.0,NaN,This collection of literature attempts to comp...,None,3/18/2008,"{""name"":""John Sillars"",""num_books"":5}","{""1_stars"":{""reviews_num"":0,""reviews_percentag...","""$0.00"""

In [9]:
df = df[df["genres"].notna() & (df["genres"] != "[]")]

In [17]:
df=df[df["num_ratings"].notna() & df["num_reviews"].notna()]

In [45]:
df=df[df["num_ratings"]>7500]

In [46]:
df

,url,id,name,author,star_rating,num_ratings,num_reviews,summary,genres,first_published,about_author,community_reviews,kindle_price
596,https://www.goodreads.com/book/show/91201.Doctors,91201.Doctors,Doctors,"[""Erich Segal""]",4.07,14625.0,582.0,"Writing with all the passion of ""Love Story"" a...","[Fiction, Romance, Medical, Medicine, Drama, C...",1/1/1988,"{""name"":""Erich Segal"",""num_books"":74,""num_foll...","{""1_stars"":{""reviews_num"":144,""reviews_percent...","""$5.99"""
677,https://www.goodreads.com/book/show/39216527-p...,39216527-paradise-rot,Paradise Rot,"[""Jenny Hval""]",3.57,17139.0,4072.0,A lyrical debut novel from a musician and arti...,"[Horror, Fiction, Queer, LGBT, Magical Realism...",1/1/2009,"{""name"":""Jenny Hval"",""num_books"":7,""num_follow...","{""1_stars"":{""reviews_num"":471,""reviews_percent...","""$7.99"""
1423,https://www.goodreads.com/book/show/21481566-t...,21481566-the-inheritance-trilogy,The Inheritance Trilogy,"[""N.K. Jemisin""]",4.29,8821.0,605.0,The Inheritance Trilogy omnibus includes the n...,"[Fantasy, Fiction, Adult, Science Fiction, Hig...",12/9/2014,"{""name"":""N.K. Jemisin"",""num_books"":115,""num_fo...","{""1_stars"":{""reviews_num"":115,""reviews_percent...","""$24.99"""
1615,https://www.goodreads.com/book/show/23249706-e...,23249706-etta-and-otto-and-russell-and-james,Etta and Otto and Russell and James,"[""Emma Hooper""]",3.66,12385.0,2167.0,"I've gone. I've never seen the water, so I've ...","[Fiction, Historical Fiction, Magical Realism,...",1/29/2015,"{""name"":""Emma Hooper"",""num_books"":9,""num_follo...","{""1_stars"":{""reviews_num"":244,""reviews_percent...","""$12.99"""
2071,https://www.goodreads.com/book/show/24357334-f...,24357334-forever-with-you,Forever with You,"[""Jennifer L. Armentrout""]",4.11,17686.0,1375.0,In the irresistibly sexy series from #1 New Yo...,"[Romance, New Adult, Contemporary, Contemporar...",9/29/2015,"{""name"":""Jennifer L. Armentrout"",""num_books"":1...","{""1_stars"":{""reviews_num"":124,""reviews_percent...","""$8.99"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6388588,https://www.goodreads.com/book/show/231869.Sei...,231869.SeinLanguage,SeinLanguage,"[""Jerry Seinfeld""]",3.61,9827.0,679.0,"Seinfeld. For more than 33 million viewers, th...","[Humor, Nonfiction, Comedy, Biography, Memoir,...",9/1/1993,"{""name"":""Jerry Seinfeld"",""num_books"":17,""num_f...","{""1_stars"":{""reviews_num"":219,""reviews_percent...",None
6388878,https://www.goodreads.com/book/show/40669887-c...,40669887-cheaper-by-the-dozen,Cheaper by the Dozen,"[""Frank B. Gilbreth Jr.""]",3.99,43245.0,2311.0,"""Dad had enough gall to be divided into three ...","[Nonfiction, Classics, Biography, Memoir, Humo...",1/1/1948,"{""name"":""Frank B. Gilbreth Jr."",""num_books"":24...","{""1_stars"":{""reviews_num"":943,""reviews_percent...","""$2.99"""
6389037,https://www.goodreads.com/book/show/7981456-a-...,7981456-a-long-walk-to-water,A Long Walk to Water,"[""Linda Sue Park""]",4.26,89846.0,11226.0,"A Long Walk to Water begins as two stories, to...","[Historical Fiction, Young Adult, Middle Grade...",11/15/2010,"{""name"":""Linda Sue Park"",""num_books"":60,""num_f...","{""1_stars"":{""reviews_num"":947,""reviews_percent...","""$9.99"""
6389645,https://www.goodreads.com/book/show/34715224-f...,34715224-flight-of-magpies,Flight of Magpies,"[""K.J. Charles""]",4.30,9694.0,1116.0,Danger in the air. Lovers on the brink.\r\n\r\...,"[Fantasy, Romance, Historical, M M Romance, Pa...",10/28/2014,"{""name"":""K.J. Charles"",""num_books"":62,""num_fol...","{""1_stars"":{""reviews_num"":34,""reviews_percenta...","""$3.99"""
6389648,https://www.goodreads.com/book/show/20662430-sand,20662430-sand,Sand,"[""Hugh Howey""]",3.97,29817.0,2214.0,The new novel from the international bestselli...,"[Science Fiction, Fiction, Dystopia, Post Apoc...",1/4/2014,"{""name"":""Hugh Howey"",""num_books"":126,""num_foll...","{""1_stars"":{""reviews_num"":306,""reviews_percent...","""$13.99"""

In [48]:
import ast
from collections import Counter
import pandas as pd

# convert string → list
#df["genres"] = df["genres"].apply(ast.literal_eval)

# count genres
genre_counts = Counter(
    genre
    for genres_list in df["genres"]
    for genre in genres_list
)

# convert to DataFrame (nice format)
genre_df = pd.DataFrame(genre_counts.items(), columns=["genre", "count"])
genre_df = genre_df.sort_values(by="count", ascending=False)

# print all
print(genre_df)

# optional: total number of distinct genres
print("\nNumber of distinct genres:", len(genre_df[genre_df["count"]>2000]))


genre_df.head(29)

         genre  count
0      Fiction  20205
17   Audiobook  10207
1      Romance   9409
16     Fantasy   8498
18       Adult   7669
..         ...    ...
801   Drinking      1
818   Stand Up      1
304     Malawi      1
815    Alchemy      1
814  Esoterica      1

[819 rows x 2 columns]

Number of distinct genres: 29

                       genre  count
0                    Fiction  20205
17                 Audiobook  10207
1                    Romance   9409
16                   Fantasy   8498
18                     Adult   7669
5               Contemporary   7586
38                   Mystery   6352
31               Young Adult   6191
39                  Thriller   4394
25        Historical Fiction   4359
6                     Novels   4245
48                 Adventure   4085
55                Nonfiction   3996
8                   Classics   3965
43          Mystery Thriller   3767
40                     Crime   3735
28                Historical   3701
41                  Suspense   3542
113               Paranormal   3060
19           Science Fiction   3032
49                     Humor   3019
30      Contemporary Romance   2949
33                 Chick Lit   2929
65                Literature   2854
71                 Childrens   2685
27             Adult Fiction   2639
23                     Magic   2582
21   Science Fiction Fantasy   2125
126            Urban Fantasy   2034

In [50]:
df.to_parquet("data/26_29_dataset.parquet", index=False)

In [11]:
df_sample=df.sample(1000,random_state=42)
df_sample

,url,id,name,author,star_rating,num_ratings,num_reviews,summary,genres,first_published,about_author,community_reviews,kindle_price
2484241,https://www.goodreads.com/book/show/2180310.Th...,2180310.The_Dimensions_of_Diplomacy,The Dimensions of Diplomacy,"[""McGeorge Bundy""]",5.00,4.0,1.0,None,"[""Politics""]",10/1/1964,"{""name"":""McGeorge Bundy"",""num_books"":24,""num_f...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
5190259,https://www.goodreads.com/book/show/10266499-s...,10266499-something-to-be-thankful-for,Something to be Thankful For,"[""Imari Jade""]",3.75,8.0,NaN,A middle-age paranoid manager and a bad boy ro...,"[""Romance""]",2/28/2011,"{""name"":""Imari Jade"",""num_books"":68,""num_follo...","{""1_stars"":{""reviews_num"":1,""reviews_percentag...","""$5.11"""
1160213,https://www.goodreads.com/book/show/11358669-b...,11358669-be-a-better-runner,"Be a Better Runner: Real World, Scientifically...","[""Sally Edwards""]",3.69,86.0,7.0,Written by marathoner and Triathlon Hall of Fa...,"[""Nonfiction"",""Health""]",1/1/2011,"{""name"":""Sally Edwards"",""num_books"":68,""num_fo...","{""1_stars"":{""reviews_num"":1,""reviews_percentag...","""$11.99"""
4773545,https://www.goodreads.com/book/show/107988.Lew...,107988.Lewis_Carroll_s_Symbolic_Logic,Lewis Carroll's Symbolic Logic,"[""Lewis Carroll""]",3.69,305.0,13.0,"Lewis Carroll’s Symbolic logic : part I, Eleme...","[""Philosophy"",""Nonfiction"",""Logic"",""Science"",""...",1/1/1896,"{""name"":""Lewis Carroll"",""num_books"":4541,""num_...","{""1_stars"":{""reviews_num"":13,""reviews_percenta...",None
2955866,https://www.goodreads.com/book/show/7804194-ti...,7804194-times-squared,Times Squared,"[""Julia DeVillers""]",4.34,1317.0,54.0,Identical twin sisters Payton and Emma Mills h...,"[""Realistic Fiction"",""Middle Grade"",""Childrens...",1/13/2011,"{""name"":""Julia DeVillers"",""num_books"":46,""num_...","{""1_stars"":{""reviews_num"":22,""reviews_percenta...","""$8.99"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6016014,https://www.goodreads.com/book/show/21817504-t...,21817504-the-first-green-wave,The First Green Wave: Pollution Probe and the ...,"[""Ryan O'Connor""]",5.00,2.0,1.0,The First Green Wave traces the rise of Ontari...,"[""History""]",11/1/2014,"{""name"":""Ryan O'Connor"",""num_books"":23}","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
5753632,https://www.goodreads.com/book/show/25758099-6...,25758099-6-orenchi-no-furo-jijou-6,オレん家のフロ事情 6 [Orenchi no Furo Jijou 6],"[""Itokichi""]",4.12,116.0,4.0,オレフロ6巻は、カニの越前VSタコの鷹巣の因縁対決、オレフロメンバーでネコ対決☆、給湯器のキ...,"[""Manga"",""Fantasy"",""Comedy"",""Slice Of Life"",""H...",10/27/2015,"{""name"":""Itokichi"",""num_books"":17,""num_followe...","{""1_stars"":{""reviews_num"":1,""reviews_percentag...","""$8.99"""
4973326,https://www.goodreads.com/book/show/3400782-ba...,3400782-battle-for-the-trinity,Battle for the Trinity: The Debate over Inclus...,"[""Donald G. Bloesch""]",4.00,9.0,5.0,"In The Battle for the Trinity, Dr. Bloesch tac...","[""Theology"",""Christianity""]",7/1/1985,"{""name"":""Donald G. Bloesch"",""num_books"":55,""nu...","{""1_stars"":{""reviews_num"":0,""reviews_percentag...",None
1727984,https://www.goodreads.com/book/show/25892657-b...,25892657-bought-by-the-doctor,Bought by the Doctor,"[""Emily Tilton""]",3.64,139.0,6.0,When she grows tired of the hypocrisy of her s...,"[""BDSM"",""Science Fiction"",""Doctors"",""Romance"",...",7/10/2015,"{""name"":""Emily Tilton"",""num_books"":209,""num_fo...","{""1_stars"":{""reviews_num"":9,""reviews_percentag...","""$4.95"""
1464786,https://www.goodreads.com/book/show/1171441.Da...,1171441.Day_One_and_Beyond,Day One and Beyond,"[""Rick Wormeli""]",4.13,99.0,14.0,Your teacher training may have provided sound ...,"[""Education"",""Teaching"",""Nonfiction"",""School""]",4/1/2003,"{""name"":""Rick Wormeli"",""num_books"":28,""num_fol...","{""1_stars"":{""reviews_num"":1,""reviews_percentag...","""$27.20"""